In [1]:
import numpy as np

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

diagonal = np.diagonal(arr)     # np.diagonal fonksiyonu, matrisin köşegenindeki elemanları döner.

print("Diagonal Elements:", diagonal)

Diagonal Elements: [10 50 90]


In [3]:
np.random.seed(42)  # Rastgele sayı üretimi için aynı sonuçları elde etmek.

random_array = np.random.randint(0, 100, (3, 3))

print(random_array)

[[51 92 14]
 [71 60 20]
 [82 86 74]]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

flattened = arr.flatten()      # Çok boyutlu bir array, tek boyutlu hale getirilir.

print(flattened)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

indices = [1, 3, 4]      # Belirli indexlerin elemanlarına toplu olarak erişmek için kullanılır.

print(arr[indices])

In [4]:
arr = np.array([10, 15, 20, 25, 30])

mask = arr % 2 == 0  # Çift sayılar için maske

print(arr[mask])

[10 20 30]


In [ ]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

merged = np.concatenate((a, b))    # np.concatenate iki veya daha fazla array'i birleştirir.

print(merged)

In [ ]:
arr = np.array([[1, 2], [3, 4]])

new_column = np.array([[5], [6]])

result = np.hstack((arr, new_column))   # np.hstack yatayda (sütun ekleme), np.vstack ise dikeyde (satır ekleme) array'leri birleştirir.

print(result)

[[1 2 5]
 [3 4 6]]


In [ ]:
arr = np.array([50, 10, 40, 20, 30])

sorted_arr = np.sort(arr)     # np.sort array elemanlarını küçükten büyüğe sıralar.

print(sorted_arr)

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])

unique_elements = np.unique(arr)    # np.unique, bir array'deki benzersiz elemanları döner.

print(unique_elements)

In [ ]:
data = np.random.randint(0, 100, 100)  # 100 elemanlı rastgele veri

hist, bins = np.histogram(data, bins=10)    # np.histogram ile veriler belirli aralıklara bölünerek histogram elde edilir.

print("Histogram:", hist)

print("Bins:", bins)

Histogram: [13  9  7  8  9 15  9 10 13  7]
Bins: [ 1.  10.8 20.6 30.4 40.2 50.  59.8 69.6 79.4 89.2 99. ]
