In [ ]:
import numpy as np

print(np.__version__)      # NumPy'nin kurulu olup olmadığını kontrol edelim

2.1.3


In [3]:
arr = np.array([1, 2, 3, 4, 5])    # Basit bir NumPy arrayi oluşturma

print(arr)

[1 2 3 4 5]


In [4]:
zeros = np.zeros((3, 3))     # 3x3 sıfırlardan oluşan bir array

print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones = np.ones((2, 5))     # 2x5 birlerden oluşan bir array

print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
random_array = np.random.rand(4, 4)    # 4x4 rastgele sayı matrisi

print(random_array)

[[0.14634317 0.23024778 0.63303218 0.51419866]
 [0.1973981  0.18708311 0.49940247 0.25977445]
 [0.38904634 0.30408014 0.34535273 0.31358123]
 [0.37264194 0.58964064 0.30424312 0.36236821]]


In [ ]:
arr = np.arange(0, 21, 2)    # 0 ile 20 arasında 2'şer artan sayılar

print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
arr = np.arange(9).reshape(3, 3)    # 1D arrayi 2D arraye dönüştürme

print(arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

squared = arr ** 2    # Array Elemanlara İşlem Yapma.

print(squared)

[ 1  4  9 16 25]


In [ ]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6], [7, 8]])  # Bu kod, iki matrisin çarpımını gerçekleştirir.

result = np.dot(a, b)           # np.dot fonksiyonu, verilen iki matrisin matris çarpımını hesaplar.

print(result)

[[19 22]
 [43 50]]


In [ ]:
arr = np.array([1, 4, 9, 16, 25])

sqrt_arr = np.sqrt(arr)      # np.sqrt fonksiyonu, her elemanın karekökünü alır.

print(sqrt_arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

sum_of_elements = np.sum(arr)   # np.sum fonksiyonu bir array'in tüm elemanlarının toplamını hesaplar.

print(sum_of_elements)

15


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

transposed = arr.T     # bir 2D array'in (matrisin) transpozunu alır. Transpoz, satır ve sütunların yer değiştirmesiyle elde edilir.



print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9])

print("Maximum:", np.max(arr))    # np.max fonksiyonu array'in en büyük elemanını bulur.

print("Minimum:", np.min(arr))    # np.min ise en küçük elemanını bulur.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

index = np.where(arr == 30)          # np.where fonksiyonu, verilen şartı sağlayan elemanların konumunu döner.

print("Index of 30:", index[0][0])   # array içinde belirli bir değerin yer aldığı indexi bulur.

Index of 30: 2
